### ISSUE TITLE
401 Not authorized

### ISSUE THREAD

**Issue by yexiaoxiao1991** [akamai-open/AkamaiOPEN-edgegrid-java#22]
the  right Authorization： EG1-HMAC-SHA256 client_token=akab-7fumbdauzqneq7yq-zalhzyep36afvacw;access_token=akab-f7lxhzj6axbnklnd-wqxemp23fgebgqb7;timestamp=20161104T15:34:14+0000;nonce=6a764a11-56c8-4541-96d6-c47cfd06e12b;signature=/U4JdnX4YMEAyDc1aqx+LxZviUC2e1VRCCZpFpPYzuk=
the Authorization I get by this library：EG1-HMAC-SHA256 client_token=akab-7fumbdauzqneq7yq-zalhzyep36afvacw;access_token=akab-f7lxhzj6axbnklnd-wqxemp23fgebgqb7;timestamp=20161104T15:34:14+0000;nonce=6a764a11-56c8-4541-96d6-c47cfd06e12b;signature=c7t85HBImm5IW/uzg0gQyzhDkxFCHCH2cxtJtqdm/wY=

what is wrong？

**Comment by mgawinec** [comment]
Can you please provide more information, e.g., code you have used to generate whole HTTP request or HTTP request itself?

It will help us reproduce and troubleshoot the issue you reported.

**Comment by yexiaoxiao1991** [comment]
![default](https://cloud.githubusercontent.com/assets/9098041/20819559/092883b2-b870-11e6-8762-5358cb949934.png)
I used the GoogleHttpClientEdgeGridRequestSignerTest ,and replace tokens with mine.Then I modify com.akamai.edgegrid.signer.EdgeGridV1Signer to make  `timestamp=20161104T15:34:14+0000;nonce=6a764a11-56c8-4541-96d6-c47cfd06e12b;`  . Last， I  ran the unit test  and  found the Authorization was not equal with the right one.

**Comment by yexiaoxiao1991** [comment]
so sorry,I made a mistake.I used post request to equal a get request.  Can u  give me a demo how to build a post content **com.google.api.client.http.HttpContent** ？  Thank u ！

**Comment by yexiaoxiao1991** [comment]
OK   I have resolved.   Maybe something wrong when I config on Luna Control Center，I can request CCU v2 apis success，but  return 401 when request CCU v3 apis

**Comment by yexiaoxiao1991** [comment]
OK  I have resolved it .thank u
