### ISSUE TITLE
Move Request.builder documentation to a separate README section

### ISSUE THREAD

**Issue by mgawinec** [akamai-open/AkamaiOPEN-edgegrid-java#23]
`Request.Builder` is of no use for people using specific binding. It will matter only for those people who will create a new binding. Perhaps, instead of describing whole architecture of the core module, we should have a section called “Creating your own binding” where we would describe core module classes and how to combine them together.

**Comment by elreydetodo** [comment]
This should be resolved by the pull request to split up the readme.
