### ISSUE TITLE
Response using the edge-grid -auth .java

### ISSUE THREAD

**Issue by gskalyan90** [akamai-open/AkamaiOPEN-edgegrid-java#5]
Could you please let us know, how do I get the response using this, I have put in all my client access tokens and base URL but no luck. Please help me in this

**Comment by Ranjodh-Singh** [comment]
Hope this will be useful [click on this link!] (https://community.akamai.com/people/B-3-196DS3L/blog/2015/07/18/complete-example-of-accessing-the-open-api-from-java)
