### ISSUE TITLE
Publish AkamaiOPEN-edgegrid-java to maven central

### ISSUE THREAD

**Issue by lucianenache** [akamai-open/AkamaiOPEN-edgegrid-java#7]
Since the project is using a pom file, it would be valid to be able to load it from maven for the sake of not having to have the library as a static jar in the project folder.

**Comment by tharrisx1** [comment]
Yes, it would be very good to get this library into a public maven repo, like every other library. We shouldn't have to maintain a mirror locally to build this.

**Comment by JuddRogers** [comment]
+1 
Please publish to maven repo.

**Comment by ktyacke** [comment]
We will be releasing a 2.0 version of the library soon and will be publishing to Maven Central at that time. This will be a breaking release, so you will need to update. Apologies that this took so long.
