### ISSUE TITLE
Requests for property resources that include "/latest/" instead of a fix version do not work. 

### ISSUE THREAD

**Issue by angelm** [akamai-open/AkamaiOPEN-edgegrid-java#8]
If you make a request for resources with "latest" instead of an actual version number (for example 80) you get an error. This works well if you curl the url by hand or use the JavaScript client.

For example requests for:

    <host>/papi/v0/properties/${propertyId}/versions/latest

are throwing an authentication error. While requests for:

    <host>/papi/v0/properties/${propertyId}/versions/80

will work perfectly. 

I haven't had time to look in detail to the root cause of the issue, but it seems that when you request for the "latest" version the server sends a redirect replacing "latest" in the url with the actual value (for example 80). But the forwarded request isn't somehow signed correctly.

**Comment by ktyacke** [comment]
Hi angelm,
This is actually an issue with the property manager API and how it responds to this request, and not an issue with the library. If you continue to experience issues with this, please try posting to https://community.akamai.com/community/developer with information about the problem.

Thanks,

Kyle
